export const emojiGroups = [
  {
    label: "Smiling & Affectionate",
    emojis: [
      { symbol: "😀", name: "Grinning Face" },
      { symbol: "😃", name: "Grinning Face with Big Eyes" },
      { symbol: "😄", name: "Grinning Face with Smiling Eyes" },
      { symbol: "😁", name: "Beaming Face with Smiling Eyes" },
      { symbol: "😆", name: "Grinning Squinting Face" },
      { symbol: "😅", name: "Grinning Face with Sweat" },
      { symbol: "🤣", name: "Rolling on the Floor Laughing" },
      { symbol: "😂", name: "Face with Tears of Joy" },
      { symbol: "🙂", name: "Slightly Smiling Face" },
      { symbol: "😉", name: "Winking Face" },
      { symbol: "😊", name: "Smiling Face with Smiling Eyes" },
      { symbol: "😇", name: "Smiling Face with Halo" },
      { symbol: "🥰", name: "Smiling Face with Hearts" },
      { symbol: "😍", name: "Smiling Face with Heart-Eyes" },
      { symbol: "🤩", name: "Star-Struck" },
      { symbol: "😘", name: "Face Blowing a Kiss" },
      { symbol: "😗", name: "Kissing Face" },
      { symbol: "☺️", name: "Smiling Face" },
      { symbol: "😚", name: "Kissing Face with Closed Eyes" },
      { symbol: "😙", name: "Kissing Face with Smiling Eyes" },
      { symbol: "😏", name: "Smirking Face" },
    ],
  },
  {
    label: "Tongues, Hands & Accessories",
    emojis: [
      { symbol: "😋", name: "Face Savoring Food" },
      { symbol: "😛", name: "Face with Tongue" },
      { symbol: "😜", name: "Winking Face with Tongue" },
      { symbol: "🤪", name: "Zany Face" },
      { symbol: "😝", name: "Squinting Face with Tongue" },
      { symbol: "🤑", name: "Money-Mouth Face" },
      { symbol: "🤗", name: "Hugging Face" },
      { symbol: "🤭", name: "Face with Hand Over Mouth" },
      { symbol: "🤫", name: "Shushing Face" },
      { symbol: "🤔", name: "Thinking Face" },
      { symbol: "🤤", name: "Drooling Face" },
      { symbol: "🤠", name: "Cowboy Hat Face" },
      { symbol: "🥳", name: "Partying Face" },
      { symbol: "😎", name: "Smiling Face with Sunglasses" },
      { symbol: "🧐", name: "Face with Monocle" },
    ],
  },
  {
    label: "Neutral & Skeptical",
    emojis: [
      { symbol: "🙃", name: "Upside-Down Face" },
      { symbol: "🤐", name: "Zipper-Mouth Face" },
      { symbol: "🤨", name: "Face with Raised Eyebrow" },
      { symbol: "😐", name: "Neutral Face" },
      { symbol: "😑", name: "Expressionless Face" },
      { symbol: "😶", name: "Face Without Mouth" },
      { symbol: "😶‍🌫️", name: "Face in Clouds" },
      { symbol: "😒", name: "Unamused Face" },
      { symbol: "🙄", name: "Face with Rolling Eyes" },
      { symbol: "😬", name: "Grimacing Face" },
      { symbol: "😮‍💨", name: "Face Exhaling" },
      { symbol: "🤥", name: "Lying Face" },
      { symbol: "🙂‍↔️", name: "Head Shaking Horizontally" },
      { symbol: "🙂‍↕️", name: "Head Shaking Vertically" },
    ],
  },
  {
    label: "Sleepy & Unwell",
    emojis: [
      { symbol: "😌", name: "Relieved Face" },
      { symbol: "😔", name: "Pensive Face" },
      { symbol: "😪", name: "Sleepy Face" },
      { symbol: "😴", name: "Sleeping Face" },
      { symbol: "😷", name: "Face with Medical Mask" },
      { symbol: "🤒", name: "Face with Thermometer" },
      { symbol: "🤕", name: "Face with Head-Bandage" },
      { symbol: "🤢", name: "Nauseated Face" },
      { symbol: "🤮", name: "Face Vomiting" },
      { symbol: "🤧", name: "Sneezing Face" },
      { symbol: "🥵", name: "Hot Face" },
      { symbol: "🥶", name: "Cold Face" },
      { symbol: "🥴", name: "Woozy Face" },
      { symbol: "😵", name: "Dizzy Face" },
      { symbol: "😵‍💫", name: "Face with Spiral Eyes" },
      { symbol: "🤯", name: "Exploding Head" },
      { symbol: "🥱", name: "Yawning Face" },
    ],
  },
  {
    label: "Concerned & Negative",
    emojis: [
      { symbol: "😕", name: "Confused Face" },
      { symbol: "😟", name: "Worried Face" },
      { symbol: "🙁", name: "Slightly Frowning Face" },
      { symbol: "☹️", name: "Frowning Face" },
      { symbol: "😮", name: "Face with Open Mouth" },
      { symbol: "😯", name: "Hushed Face" },
      { symbol: "😲", name: "Astonished Face" },
      { symbol: "😳", name: "Flushed Face" },
      { symbol: "🥺", name: "Pleading Face" },
      { symbol: "😦", name: "Frowning Face with Open Mouth" },
      { symbol: "😧", name: "Anguished Face" },
      { symbol: "😨", name: "Fearful Face" },
      { symbol: "😰", name: "Anxious Face with Sweat" },
      { symbol: "😥", name: "Sad but Relieved Face" },
      { symbol: "😢", name: "Crying Face" },
      { symbol: "😭", name: "Loudly Crying Face" },
      { symbol: "😖", name: "Confounded Face" },
      { symbol: "😣", name: "Persevering Face" },
      { symbol: "😞", name: "Disappointed Face" },
      { symbol: "😓", name: "Downcast Face with Sweat" },
      { symbol: "😩", name: "Weary Face" },
      { symbol: "😫", name: "Tired Face" },
      { symbol: "😤", name: "Face with Steam From Nose" },
      { symbol: "😡", name: "Pouting Face" },
      { symbol: "😠", name: "Angry Face" },
      { symbol: "🤬", name: "Face with Symbols on Mouth" },
    ],
  },
  {
    label: "Costume, Creature & Animal",
    emojis: [
      { symbol: "😈", name: "Smiling Face with Horns" },
      { symbol: "👿", name: "Angry Face with Horns" },
      { symbol: "💀", name: "Skull" },
      { symbol: "☠️", name: "Skull and Crossbones" },
      { symbol: "💩", name: "Pile of Poo" },
      { symbol: "🤡", name: "Clown Face" },
      { symbol: "👹", name: "Ogre" },
      { symbol: "👺", name: "Goblin" },
      { symbol: "👻", name: "Ghost" },
      { symbol: "👽", name: "Alien" },
      { symbol: "👾", name: "Alien Monster" },
      { symbol: "🤖", name: "Robot" },
      { symbol: "😺", name: "Grinning Cat" },
      { symbol: "😸", name: "Grinning Cat with Smiling Eyes" },
      { symbol: "😹", name: "Cat with Tears of Joy" },
      { symbol: "😻", name: "Smiling Cat with Heart-Eyes" },
      { symbol: "😼", name: "Cat with Wry Smile" },
      { symbol: "😽", name: "Kissing Cat" },
      { symbol: "🙀", name: "Weary Cat" },
      { symbol: "😿", name: "Crying Cat" },
      { symbol: "😾", name: "Pouting Cat" },
      { symbol: "🙈", name: "See-No-Evil Monkey" },
      { symbol: "🙉", name: "Hear-No-Evil Monkey" },
      { symbol: "🙊", name: "Speak-No-Evil Monkey" },
    ],
  },
];
