export const users = [
  {
    userId: "user99",
    username: "Adrish",
    email: "adrishghosh23@gmail.com",
    password: "1234",
    avatar: "",
    channels: ["channel99", "channel100"],
    activeChannel: "channel99",
  },
  {
    username: "TechEnthusiast2024",
    email: "tech.enthusiast@example.com",
    password: "hashedPassword123",
    avatar: "https://avatar.dicebear.com/api/avataaars/tech-enthusiast.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "CodeMaster",
    email: "codemaster@example.com",
    password: "hashedPassword456",
    avatar: "https://avatar.dicebear.com/api/avataaars/code-master.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "DevGuru",
    email: "devguru@example.com",
    password: "hashedPassword789",
    avatar: "https://avatar.dicebear.com/api/avataaars/dev-guru.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "WebDevPro",
    email: "webdevpro@example.com",
    password: "hashedPasswordABC",
    avatar: "https://avatar.dicebear.com/api/avataaars/webdev-pro.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "CodingNinja",
    email: "codingninja@example.com",
    password: "hashedPasswordDEF",
    avatar: "https://avatar.dicebear.com/api/avataaars/coding-ninja.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "ReactDeveloper",
    email: "reactdev@example.com",
    password: "hashedPasswordGHI",
    avatar: "https://avatar.dicebear.com/api/avataaars/react-developer.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "JSExpert",
    email: "jsexpert@example.com",
    password: "hashedPasswordJKL",
    avatar: "https://avatar.dicebear.com/api/avataaars/js-expert.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "FrontEndWiz",
    email: "frontendwiz@example.com",
    password: "hashedPasswordMNO",
    avatar: "https://avatar.dicebear.com/api/avataaars/frontend-wiz.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "FullStackDev",
    email: "fullstackdev@example.com",
    password: "hashedPasswordPQR",
    avatar: "https://avatar.dicebear.com/api/avataaars/fullstack-dev.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "APIBuilder",
    email: "apibuilder@example.com",
    password: "hashedPasswordSTU",
    avatar: "https://avatar.dicebear.com/api/avataaars/api-builder.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "GameDevMaster",
    email: "gamedevmaster@example.com",
    password: "hashedPasswordVWX",
    avatar: "https://avatar.dicebear.com/api/avataaars/gamedev-master.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "CPlusPlusGuru",
    email: "cppguru@example.com",
    password: "hashedPasswordYZA",
    avatar: "https://avatar.dicebear.com/api/avataaars/cpp-guru.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "UnityDeveloper",
    email: "unitydev@example.com",
    password: "hashedPasswordBCD",
    avatar: "https://avatar.dicebear.com/api/avataaars/unity-developer.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "UnrealExpert",
    email: "unrealexpert@example.com",
    password: "hashedPasswordEFG",
    avatar: "https://avatar.dicebear.com/api/avataaars/unreal-expert.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "GodotFan",
    email: "godotfan@example.com",
    password: "hashedPasswordHIJ",
    avatar: "https://avatar.dicebear.com/api/avataaars/godot-fan.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "IndieGameDev",
    email: "indiegamedev@example.com",
    password: "hashedPasswordKLM",
    avatar: "https://avatar.dicebear.com/api/avataaars/indie-gamedev.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "HordeGameMaker",
    email: "hordegamemaker@example.com",
    password: "hashedPasswordNOP",
    avatar: "https://avatar.dicebear.com/api/avataaars/horde-gamemaker.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "SurvivalGamePro",
    email: "survivalgamepro@example.com",
    password: "hashedPasswordQRS",
    avatar: "https://avatar.dicebear.com/api/avataaars/survival-gamepro.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "GameEngineExplorer",
    email: "gameengineexplorer@example.com",
    password: "hashedPasswordTUV",
    avatar: "https://avatar.dicebear.com/api/avataaars/gameengine-explorer.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "BattleGameCreator",
    email: "battlegamecreator@example.com",
    password: "hashedPasswordWXY",
    avatar: "https://avatar.dicebear.com/api/avataaars/battle-gamecreator.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "SitarMelody",
    email: "sitarmelody@example.com",
    password: "hashedPasswordZAB",
    avatar: "https://avatar.dicebear.com/api/avataaars/sitar-melody.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "IndianClassical",
    email: "indianclassical@example.com",
    password: "hashedPasswordCDE",
    avatar: "https://avatar.dicebear.com/api/avataaars/indian-classical.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "BurningManFan",
    email: "burningmanfan@example.com",
    password: "hashedPasswordFGH",
    avatar: "https://avatar.dicebear.com/api/avataaars/burningman-fan.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "MentalHealthAdvocate",
    email: "mentalhealthadvocate@example.com",
    password: "hashedPasswordIJK",
    avatar:
      "https://avatar.dicebear.com/api/avataaars/mentalhealth-advocate.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "VaranasiLover",
    email: "varanasilover@example.com",
    password: "hashedPasswordLMN",
    avatar: "https://avatar.dicebear.com/api/avataaars/varanasi-lover.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "PopMusicFan",
    email: "popmusicfan@example.com",
    password: "hashedPasswordOPQ",
    avatar: "https://avatar.dicebear.com/api/avataaars/popmusic-fan.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "LadyGagaSupporter",
    email: "ladygagasupporter@example.com",
    password: "hashedPasswordRST",
    avatar: "https://avatar.dicebear.com/api/avataaars/ladygaga-supporter.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "BrunoMarsFan",
    email: "brunomarsfan@example.com",
    password: "hashedPasswordUVW",
    avatar: "https://avatar.dicebear.com/api/avataaars/brunomars-fan.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "CollabMusicLover",
    email: "collabmusiclover@example.com",
    password: "hashedPasswordXYZ",
    avatar: "https://avatar.dicebear.com/api/avataaars/collabmusic-lover.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "SmileWithMusic",
    email: "smilewithmusic@example.com",
    password: "hashedPasswordABC1",
    avatar: "https://avatar.dicebear.com/api/avataaars/smile-withmusic.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "CricketEnthusiast",
    email: "cricketenthusiast@example.com",
    password: "hashedPasswordDEF1",
    avatar: "https://avatar.dicebear.com/api/avataaars/cricket-enthusiast.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "EnglandCricketFan",
    email: "englandcricketfan@example.com",
    password: "hashedPasswordGHI1",
    avatar: "https://avatar.dicebear.com/api/avataaars/england-cricketfan.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "SophieEcclestoneSupporter",
    email: "sophieecclestone@example.com",
    password: "hashedPasswordJKL1",
    avatar: "https://avatar.dicebear.com/api/avataaars/sophie-supporter.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "LordsGroundVisitor",
    email: "lordsgroundvisitor@example.com",
    password: "hashedPasswordMNO1",
    avatar: "https://avatar.dicebear.com/api/avataaars/lords-visitor.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "IndiaCricketSupporter",
    email: "indiacricketsupporter@example.com",
    password: "hashedPasswordPQR1",
    avatar:
      "https://avatar.dicebear.com/api/avataaars/india-cricketsupporter.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "ShaneWarneFan",
    email: "shanewarnefan@example.com",
    password: "hashedPasswordSTU1",
    avatar: "https://avatar.dicebear.com/api/avataaars/shanewarne-fan.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "AustraliaCricketAnalyst",
    email: "australiacricketanalyst@example.com",
    password: "hashedPasswordVWX1",
    avatar: "https://avatar.dicebear.com/api/avataaars/australia-analyst.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "CaptainshipExpert",
    email: "captainshipexpert@example.com",
    password: "hashedPasswordYZA1",
    avatar: "https://avatar.dicebear.com/api/avataaars/captainship-expert.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "TalkSportListener",
    email: "talksportlistener@example.com",
    password: "hashedPasswordBCD1",
    avatar: "https://avatar.dicebear.com/api/avataaars/talksport-listener.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "CricketPodcastFan",
    email: "cricketpodcastfan@example.com",
    password: "hashedPasswordEFG1",
    avatar: "https://avatar.dicebear.com/api/avataaars/cricket-podcastfan.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "SpaceExplorer",
    email: "spaceexplorer@example.com",
    password: "hashedPasswordHIJ1",
    avatar: "https://avatar.dicebear.com/api/avataaars/space-explorer.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "ISROEnthusiast",
    email: "isroenthusiast@example.com",
    password: "hashedPasswordKLM1",
    avatar: "https://avatar.dicebear.com/api/avataaars/isro-enthusiast.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "AxiomMissionFollower",
    email: "axiommissionfollower@example.com",
    password: "hashedPasswordNOP1",
    avatar: "https://avatar.dicebear.com/api/avataaars/axiom-follower.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "IndianAstronautSupporter",
    email: "indianastronautsupporter@example.com",
    password: "hashedPasswordQRS1",
    avatar:
      "https://avatar.dicebear.com/api/avataaars/indian-astronautsupporter.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "ISSWatcher",
    email: "isswatcher@example.com",
    password: "hashedPasswordTUV1",
    avatar: "https://avatar.dicebear.com/api/avataaars/iss-watcher.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "HealthAdvocate",
    email: "healthadvocate@example.com",
    password: "hashedPasswordWXY1",
    avatar: "https://avatar.dicebear.com/api/avataaars/health-advocate.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "JapaneseCultureLover",
    email: "japaneseculturelover@example.com",
    password: "hashedPasswordZAB1",
    avatar:
      "https://avatar.dicebear.com/api/avataaars/japanese-culturelover.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "LongevitySeeker",
    email: "longevityseeker@example.com",
    password: "hashedPasswordCDE1",
    avatar: "https://avatar.dicebear.com/api/avataaars/longevity-seeker.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "NutritionExpert",
    email: "nutritionexpert@example.com",
    password: "hashedPasswordFGH1",
    avatar: "https://avatar.dicebear.com/api/avataaars/nutrition-expert.png",
    channels: [],
    activeChannel: "",
  },
  {
    username: "WellnessGuru",
    email: "wellnessguru@example.com",
    password: "hashedPasswordIJK1",
    avatar: "https://avatar.dicebear.com/api/avataaars/wellness-guru.png",
    channels: [],
    activeChannel: "",
  },

  {
    username: "6PackProgrammer",
    email: "sixpackprogrammer@example.com",
    password: "hashedPasswordUPL1",
    avatar:
      "https://yt3.ggpht.com/8DHXGxqNVJuiT1bnxECydjk4bRfGRCVHuR0MyAxtkjxa0k0PC_uBU-jCOswGnd_5HaTQRHj_eg=s48-c-k-c0x00ffffff-no-rj",
    channels: ["channel01"],
    activeChannel: "channel01",
  },
  {
    username: "DaveGrayTeaches",
    email: "davegray@example.com",
    password: "hashedPasswordUPL2",
    avatar:
      "https://yt3.ggpht.com/nv365KiAJyURPEBZyCh0SV3hSBnZXbvVXrzRwcNDfgUpXPn9-3_4PY0SkQrAJWnzQOxKqfUtrQ=s48-c-k-c0x00ffffff-no-rj",
    channels: ["channel02"],
    activeChannel: "channel02",
  },
  {
    username: "ThisIsGameDev",
    email: "thisisgamedev@example.com",
    password: "hashedPasswordUPL3",
    avatar:
      "https://yt3.ggpht.com/FrPiiMsu6RDPDoV8rP_RtTNV_lOCSa5k-FWXtflTdqkHeDkZZaSsHnYIE0WQJcHRnZCuEsQO2SM=s48-c-k-c0x00ffffff-no-rj",
    channels: ["channel03"],
    activeChannel: "channel03",
  },
  {
    username: "GameDevTV",
    email: "gamedevtv@example.com",
    password: "hashedPasswordUPL4",
    avatar:
      "https://yt3.ggpht.com/Yc8yE0uzd0bx08ir-xkPcvIsFy0WF1EK2JKjCYBaSXs4QNkqGtarI9hk0I5ymMPFC5YHFS-oaQ=s48-c-k-c0x00ffffff-no-rj",
    channels: ["channel04"],
    activeChannel: "channel04",
  },
  {
    username: "RishabRikhiramSharma",
    email: "rishabsharma@example.com",
    password: "hashedPasswordUPL5",
    avatar:
      "https://yt3.ggpht.com/g1G8SyHMybBz6riIg9n9rAFmAeF7K_O9P7H-LLrr7Y80qLeXvM7x2RWiFI8BhBe0vG8paSgLEw=s48-c-k-c0x00ffffff-no-rj",
    channels: ["channel05"],
    activeChannel: "channel05",
  },
  {
    username: "LadyGagaOfficial",
    email: "ladygaga@example.com",
    password: "hashedPasswordUPL6",
    avatar:
      "https://yt3.ggpht.com/lM8HHBd5BZtP_-Dh1i3n1Z4teVW8v2KTG-hsS83yXUiK0K6krkk1XNEFbho3uwH-CS-FQpnlHw=s48-c-k-c0x00ffffff-no-rj",
    channels: ["channel06"],
    activeChannel: "channel06",
  },
  {
    username: "EnglandWalesCricketBoard",
    email: "ecb@example.com",
    password: "hashedPasswordUPL7",
    avatar:
      "https://yt3.ggpht.com/Kvp63X5q5rUFXpy73Nwj3HYhUnymjVJyZjRGDEhUii26M8Ufr-30l9yekzDPcIj7Hj3bELCSGA=s68-c-k-c0x00ffffff-no-rj",
    channels: ["channel07"],
    activeChannel: "channel07",
  },
  {
    username: "TalkSportCricket",
    email: "talksportcricket@example.com",
    password: "hashedPasswordUPL8",
    avatar:
      "https://yt3.ggpht.com/GI--0ywaFfHw_aknt9TtqXN892773ijUB3pugDcH5kUQ-M9nkqTk4zkf_HNTBB0RpNzKG-XQ=s48-c-k-c0x00ffffff-no-rj",
    channels: ["channel08"],
    activeChannel: "channel08",
  },
  {
    username: "IndiaTodayOfficial",
    email: "indiatoday@example.com",
    password: "hashedPasswordUPL9",
    avatar:
      "https://yt3.ggpht.com/T2CFyCYOvSqnAJZL2HTDrLw-9Z48j97WXjHn41HoPXZ-ZaeH02WAFSBe2cDKRWNcjZR5lhtKcg=s48-c-k-c0x00ffffff-no-rj",
    channels: ["channel09"],
    activeChannel: "channel09",
  },
  {
    username: "HealthyLongLife",
    email: "healthylonglife@example.com",
    password: "hashedPasswordUPL10",
    avatar:
      "https://yt3.ggpht.com/GHfOgy_asLxYSXRuCUNqIYUnfKWFsjCO0ibIHyWopaXFjY1ACoqWQeVICUmAQR1nlgjIDfTseg=s48-c-k-c0x00ffffff-no-rj",
    channels: ["channel10"],
    activeChannel: "channel10",
  },
];
