export const users = [
  // {
  //   userId: "user99",
  //   username: "Adrish",
  //   email: "adrishghosh23@gmail.com",
  //   password: "1234",
  //   avatar: "",
  //   channels: ["channel99", "channel100"],
  //   activeChannelId: "channel99",
  // },
  // {
  //   username: "TechEnthusiast2024",
  //   email: "tech.enthusiast@example.com",
  //   password: "hashedPassword123",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/tech-enthusiast.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "CodeMaster",
  //   email: "codemaster@example.com",
  //   password: "hashedPassword456",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/code-master.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "DevGuru",
  //   email: "devguru@example.com",
  //   password: "hashedPassword789",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/dev-guru.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "WebDevPro",
  //   email: "webdevpro@example.com",
  //   password: "hashedPasswordABC",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/webdev-pro.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "CodingNinja",
  //   email: "codingninja@example.com",
  //   password: "hashedPasswordDEF",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/coding-ninja.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "ReactDeveloper",
  //   email: "reactdev@example.com",
  //   password: "hashedPasswordGHI",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/react-developer.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "JSExpert",
  //   email: "jsexpert@example.com",
  //   password: "hashedPasswordJKL",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/js-expert.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "FrontEndWiz",
  //   email: "frontendwiz@example.com",
  //   password: "hashedPasswordMNO",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/frontend-wiz.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "FullStackDev",
  //   email: "fullstackdev@example.com",
  //   password: "hashedPasswordPQR",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/fullstack-dev.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "APIBuilder",
  //   email: "apibuilder@example.com",
  //   password: "hashedPasswordSTU",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/api-builder.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "GameDevMaster",
  //   email: "gamedevmaster@example.com",
  //   password: "hashedPasswordVWX",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/gamedev-master.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "CPlusPlusGuru",
  //   email: "cppguru@example.com",
  //   password: "hashedPasswordYZA",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/cpp-guru.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "UnityDeveloper",
  //   email: "unitydev@example.com",
  //   password: "hashedPasswordBCD",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/unity-developer.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "UnrealExpert",
  //   email: "unrealexpert@example.com",
  //   password: "hashedPasswordEFG",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/unreal-expert.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "GodotFan",
  //   email: "godotfan@example.com",
  //   password: "hashedPasswordHIJ",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/godot-fan.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "IndieGameDev",
  //   email: "indiegamedev@example.com",
  //   password: "hashedPasswordKLM",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/indie-gamedev.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "HordeGameMaker",
  //   email: "hordegamemaker@example.com",
  //   password: "hashedPasswordNOP",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/horde-gamemaker.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "SurvivalGamePro",
  //   email: "survivalgamepro@example.com",
  //   password: "hashedPasswordQRS",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/survival-gamepro.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "GameEngineExplorer",
  //   email: "gameengineexplorer@example.com",
  //   password: "hashedPasswordTUV",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/gameengine-explorer.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "BattleGameCreator",
  //   email: "battlegamecreator@example.com",
  //   password: "hashedPasswordWXY",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/battle-gamecreator.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "SitarMelody",
  //   email: "sitarmelody@example.com",
  //   password: "hashedPasswordZAB",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/sitar-melody.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "IndianClassical",
  //   email: "indianclassical@example.com",
  //   password: "hashedPasswordCDE",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/indian-classical.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "BurningManFan",
  //   email: "burningmanfan@example.com",
  //   password: "hashedPasswordFGH",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/burningman-fan.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "MentalHealthAdvocate",
  //   email: "mentalhealthadvocate@example.com",
  //   password: "hashedPasswordIJK",
  //   avatar:
  //     "https://avatar.dicebear.com/api/avataaars/mentalhealth-advocate.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "VaranasiLover",
  //   email: "varanasilover@example.com",
  //   password: "hashedPasswordLMN",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/varanasi-lover.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "PopMusicFan",
  //   email: "popmusicfan@example.com",
  //   password: "hashedPasswordOPQ",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/popmusic-fan.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "LadyGagaSupporter",
  //   email: "ladygagasupporter@example.com",
  //   password: "hashedPasswordRST",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/ladygaga-supporter.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "BrunoMarsFan",
  //   email: "brunomarsfan@example.com",
  //   password: "hashedPasswordUVW",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/brunomars-fan.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "CollabMusicLover",
  //   email: "collabmusiclover@example.com",
  //   password: "hashedPasswordXYZ",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/collabmusic-lover.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "SmileWithMusic",
  //   email: "smilewithmusic@example.com",
  //   password: "hashedPasswordABC1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/smile-withmusic.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "CricketEnthusiast",
  //   email: "cricketenthusiast@example.com",
  //   password: "hashedPasswordDEF1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/cricket-enthusiast.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "EnglandCricketFan",
  //   email: "englandcricketfan@example.com",
  //   password: "hashedPasswordGHI1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/england-cricketfan.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "SophieEcclestoneSupporter",
  //   email: "sophieecclestone@example.com",
  //   password: "hashedPasswordJKL1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/sophie-supporter.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "LordsGroundVisitor",
  //   email: "lordsgroundvisitor@example.com",
  //   password: "hashedPasswordMNO1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/lords-visitor.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "IndiaCricketSupporter",
  //   email: "indiacricketsupporter@example.com",
  //   password: "hashedPasswordPQR1",
  //   avatar:
  //     "https://avatar.dicebear.com/api/avataaars/india-cricketsupporter.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "ShaneWarneFan",
  //   email: "shanewarnefan@example.com",
  //   password: "hashedPasswordSTU1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/shanewarne-fan.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "AustraliaCricketAnalyst",
  //   email: "australiacricketanalyst@example.com",
  //   password: "hashedPasswordVWX1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/australia-analyst.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "CaptainshipExpert",
  //   email: "captainshipexpert@example.com",
  //   password: "hashedPasswordYZA1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/captainship-expert.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "TalkSportListener",
  //   email: "talksportlistener@example.com",
  //   password: "hashedPasswordBCD1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/talksport-listener.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "CricketPodcastFan",
  //   email: "cricketpodcastfan@example.com",
  //   password: "hashedPasswordEFG1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/cricket-podcastfan.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "SpaceExplorer",
  //   email: "spaceexplorer@example.com",
  //   password: "hashedPasswordHIJ1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/space-explorer.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "ISROEnthusiast",
  //   email: "isroenthusiast@example.com",
  //   password: "hashedPasswordKLM1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/isro-enthusiast.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "AxiomMissionFollower",
  //   email: "axiommissionfollower@example.com",
  //   password: "hashedPasswordNOP1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/axiom-follower.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "IndianAstronautSupporter",
  //   email: "indianastronautsupporter@example.com",
  //   password: "hashedPasswordQRS1",
  //   avatar:
  //     "https://avatar.dicebear.com/api/avataaars/indian-astronautsupporter.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "ISSWatcher",
  //   email: "isswatcher@example.com",
  //   password: "hashedPasswordTUV1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/iss-watcher.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "HealthAdvocate",
  //   email: "healthadvocate@example.com",
  //   password: "hashedPasswordWXY1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/health-advocate.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "JapaneseCultureLover",
  //   email: "japaneseculturelover@example.com",
  //   password: "hashedPasswordZAB1",
  //   avatar:
  //     "https://avatar.dicebear.com/api/avataaars/japanese-culturelover.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "LongevitySeeker",
  //   email: "longevityseeker@example.com",
  //   password: "hashedPasswordCDE1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/longevity-seeker.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "NutritionExpert",
  //   email: "nutritionexpert@example.com",
  //   password: "hashedPasswordFGH1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/nutrition-expert.png",
  //   channels: [],
  //   activeChannelId: "",
  // },
  // {
  //   username: "WellnessGuru",
  //   email: "wellnessguru@example.com",
  //   password: "hashedPasswordIJK1",
  //   avatar: "https://avatar.dicebear.com/api/avataaars/wellness-guru.png",
  //   channels: [],
  //   activeChannelId: "",
  // },

  {
    username: "6PackProgrammer",
    email: "sixpackprogrammer@example.com",
    password: "hashedPasswordUPL1",
    avatar:
      "https://yt3.ggpht.com/8DHXGxqNVJuiT1bnxECydjk4bRfGRCVHuR0MyAxtkjxa0k0PC_uBU-jCOswGnd_5HaTQRHj_eg=s48-c-k-c0x00ffffff-no-rj",
    channels: ["68a0652d88e7fa049f41c54f"],
    activeChannelId: "68a0652d88e7fa049f41c54f",
  },
  {
    username: "DaveGrayTeaches",
    email: "davegray@example.com",
    password: "hashedPasswordUPL2",
    avatar:
      "https://yt3.ggpht.com/nv365KiAJyURPEBZyCh0SV3hSBnZXbvVXrzRwcNDfgUpXPn9-3_4PY0SkQrAJWnzQOxKqfUtrQ=s48-c-k-c0x00ffffff-no-rj",
    channels: ["68a0652d88e7fa049f41c550"],
    activeChannelId: "68a0652d88e7fa049f41c550",
  },
  {
    username: "ThisIsGameDev",
    email: "thisisgamedev@example.com",
    password: "hashedPasswordUPL3",
    avatar:
      "https://yt3.ggpht.com/FrPiiMsu6RDPDoV8rP_RtTNV_lOCSa5k-FWXtflTdqkHeDkZZaSsHnYIE0WQJcHRnZCuEsQO2SM=s48-c-k-c0x00ffffff-no-rj",
    channels: ["68a0652d88e7fa049f41c551"],
    activeChannelId: "68a0652d88e7fa049f41c551",
  },
  {
    username: "GameDevTV",
    email: "gamedevtv@example.com",
    password: "hashedPasswordUPL4",
    avatar:
      "https://yt3.ggpht.com/Yc8yE0uzd0bx08ir-xkPcvIsFy0WF1EK2JKjCYBaSXs4QNkqGtarI9hk0I5ymMPFC5YHFS-oaQ=s48-c-k-c0x00ffffff-no-rj",
    channels: ["68a0652d88e7fa049f41c552"],
    activeChannelId: "68a0652d88e7fa049f41c552",
  },
  {
    username: "RishabRikhiramSharma",
    email: "rishabsharma@example.com",
    password: "hashedPasswordUPL5",
    avatar:
      "https://yt3.ggpht.com/g1G8SyHMybBz6riIg9n9rAFmAeF7K_O9P7H-LLrr7Y80qLeXvM7x2RWiFI8BhBe0vG8paSgLEw=s48-c-k-c0x00ffffff-no-rj",
    channels: ["68a0652d88e7fa049f41c553"],
    activeChannelId: "68a0652d88e7fa049f41c553",
  },
  {
    username: "LadyGagaOfficial",
    email: "ladygaga@example.com",
    password: "hashedPasswordUPL6",
    avatar:
      "https://yt3.ggpht.com/lM8HHBd5BZtP_-Dh1i3n1Z4teVW8v2KTG-hsS83yXUiK0K6krkk1XNEFbho3uwH-CS-FQpnlHw=s48-c-k-c0x00ffffff-no-rj",
    channels: ["68a0652d88e7fa049f41c554"],
    activeChannelId: "68a0652d88e7fa049f41c554",
  },
  {
    username: "EnglandWalesCricketBoard",
    email: "ecb@example.com",
    password: "hashedPasswordUPL7",
    avatar:
      "https://yt3.ggpht.com/Kvp63X5q5rUFXpy73Nwj3HYhUnymjVJyZjRGDEhUii26M8Ufr-30l9yekzDPcIj7Hj3bELCSGA=s68-c-k-c0x00ffffff-no-rj",
    channels: ["68a0652d88e7fa049f41c555"],
    activeChannelId: "68a0652d88e7fa049f41c555",
  },
  {
    username: "TalkSportCricket",
    email: "talksportcricket@example.com",
    password: "hashedPasswordUPL8",
    avatar:
      "https://yt3.ggpht.com/GI--0ywaFfHw_aknt9TtqXN892773ijUB3pugDcH5kUQ-M9nkqTk4zkf_HNTBB0RpNzKG-XQ=s48-c-k-c0x00ffffff-no-rj",
    channels: ["68a0652d88e7fa049f41c556"],
    activeChannelId: "68a0652d88e7fa049f41c556",
  },
  {
    username: "IndiaTodayOfficial",
    email: "indiatoday@example.com",
    password: "hashedPasswordUPL9",
    avatar:
      "https://yt3.ggpht.com/T2CFyCYOvSqnAJZL2HTDrLw-9Z48j97WXjHn41HoPXZ-ZaeH02WAFSBe2cDKRWNcjZR5lhtKcg=s48-c-k-c0x00ffffff-no-rj",
    channels: ["68a0652d88e7fa049f41c557"],
    activeChannelId: "68a0652d88e7fa049f41c557",
  },
  {
    username: "HealthyLongLife",
    email: "healthylonglife@example.com",
    password: "hashedPasswordUPL10",
    avatar:
      "https://yt3.ggpht.com/GHfOgy_asLxYSXRuCUNqIYUnfKWFsjCO0ibIHyWopaXFjY1ACoqWQeVICUmAQR1nlgjIDfTseg=s48-c-k-c0x00ffffff-no-rj",
    channels: ["68a0652d88e7fa049f41c558"],
    activeChannelId: "68a0652d88e7fa049f41c558",
  },
];
